Spirits:
  Base Game:
    - Lightning's Swift Strike
    - River Surges in Sunlight
    - Shadows Flicker Like Flame
    - Vital Strength of the Earth
    - A Spread of Rampant Green
    - Thunderspeaker
    - Bringer of Dreams and Nightmares
    - Ocean's Hungry Grasp
  Branch and Claw:
    - Keeper of the Forbidden Wilds
    - Sharp Fangs Behind the Leaves
  Promotion Pack 1:
    - Heart of the Wildfire
    - Serpent Slumbering Beneath the Island
  Jagged Earth:
    - Grinning Trickster Stirs Up Trouble
    - Lure of the Deep Wilderness
    - Many Minds Move as One
    - Shifting Memory of Ages
    - Stone's Unyielding Defiance
    - Volcano Looming High
    - Shroud of Silent Mist
    - Vengeance as a Burning Plague
    - Fractured Days Split the Sky
    - Starlight Seeks Its Form
  Promotion Pack 2:
    - Downpour Drenches the World
    - Finder of Paths Unseen
  Horizons of Spirit Island:
    - Devouring Teeth Lurk Underfoot
    - Eyes Watch From the Trees
    - Fathomless Mud of the Swamp
    - Rising Heat of Stone and Sand
    - Sun-Bright Whirlwind
Adversaries:
  Base Game:
    - Brandenburg-Prussia
    - England
    - Sweden
  Promotion Pack 1:
  Branch and Claw:
    - France
  Jagged Earth:
    - Habsburg Monarchy
    - Russia
  Promotion Pack 2:
    - Scotland
  Horizons of Spirit Island:
Scenarios:
  Base Game:
    - Blitz: 0
    - Guard the Isle's Heart: 0
    - Rituals of Terror: 3
    - Dahan Insurrection: 4
  Promotion Pack 1:
  Branch and Claw:
    - Second Wave: 1
    - Powers Long Forgotten: 1
    - Ward the Shores: 2
    - Rituals of the Destroying Flame: 3
  Jagged Earth:
    - Elemental Invocation: 1
    - Despicable Theft: 2
    - The Great River: 3
  Promotion Pack 2:
    - A Diversity of Spirits: 0
    - Varied Terrains: 2
  Horizons of Spirit Island:
